/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "JWT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EmailSender": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "NEON_DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BucketImgQr": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "doc": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}
